// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WHS.Infrastructure.Migrations
{
    [DbContext(typeof(WarehouseDbContext))]
    [Migration("20250402120150_update-tables shipment")]
    partial class updatetablesshipment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WHS.Domain.Entities.Account.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("WHS.Domain.Entities.Audit.ActionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ElapsedSeconds")
                        .HasColumnType("float");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ActionLogs");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Code.Brand", b =>
                {
                    b.Property<Guid>("BrandGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("BrandDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BrandGUID");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Code.CodeTable", b =>
                {
                    b.Property<Guid>("TableGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TableDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TableGUID");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("CodeTables");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Code.CodeTableValue", b =>
                {
                    b.Property<Guid>("TableValueGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<Guid>("TableGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ValueName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TableValueGUID");

                    b.HasIndex("TableGUID");

                    b.ToTable("CodeTableValues");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Code.Country", b =>
                {
                    b.Property<Guid>("CountryGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryGUID");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Code.CountryLocation", b =>
                {
                    b.Property<Guid>("LocationGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CountryGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocationGUID");

                    b.HasIndex("CountryGUID");

                    b.ToTable("CountryLocations");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Code.DeterminerType", b =>
                {
                    b.Property<Guid>("DeterminerTypeGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeterminerTypeGUID");

                    b.ToTable("DeterminerTypes");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Code.DutyStation", b =>
                {
                    b.Property<Guid>("DutyStationGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DutyStationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("InstitutionGUID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DutyStationGUID");

                    b.HasIndex("InstitutionGUID");

                    b.ToTable("DutyStations");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Code.InstitutionByCountry", b =>
                {
                    b.Property<Guid>("InstitutionGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CountryGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InstitutioName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganizationGUID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("InstitutionGUID");

                    b.HasIndex("CountryGUID");

                    b.HasIndex("OrganizationGUID");

                    b.ToTable("InstitutionByCountries");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Code.Organization", b =>
                {
                    b.Property<Guid>("OrganizationGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OrganizationCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrganizationGUID");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Code.Product", b =>
                {
                    b.Property<Guid>("ProductGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<Guid>("BrandGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductSubCategoryGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductTypeGUID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProductGUID");

                    b.HasIndex("BrandGUID");

                    b.HasIndex("ProductSubCategoryGUID");

                    b.HasIndex("ProductTypeGUID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Code.ProductByWarehouse", b =>
                {
                    b.Property<Guid>("ProductByWarehouseGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WarehouseGUID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProductByWarehouseGUID");

                    b.HasIndex("ProductGUID");

                    b.HasIndex("WarehouseGUID");

                    b.ToTable("ProductByWarehouse");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Code.ProductCategory", b =>
                {
                    b.Property<Guid>("ProductCategoryGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductCategoryGUID");

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Code.ProductDeterminer", b =>
                {
                    b.Property<Guid>("ProductDeterminerGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeterminerTypeGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductGUID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProductDeterminerGUID");

                    b.HasIndex("DeterminerTypeGUID");

                    b.HasIndex("ProductGUID");

                    b.ToTable("ProductDeterminers");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Code.ProductFeature", b =>
                {
                    b.Property<Guid>("ProductFeatureGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FeatureName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeatureValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductGUID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProductFeatureGUID");

                    b.HasIndex("ProductGUID");

                    b.ToTable("ProductFeatures");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Code.ProductSubCategory", b =>
                {
                    b.Property<Guid>("ProductSubCategoryGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductCategoryGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SubCategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductSubCategoryGUID");

                    b.HasIndex("ProductCategoryGUID");

                    b.ToTable("ProductSubCategories");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Code.ProductType", b =>
                {
                    b.Property<Guid>("ProductTypeGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductTypeGUID");

                    b.ToTable("ProductTypes");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Code.RequesterType", b =>
                {
                    b.Property<Guid>("RequesterTypeGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequesterCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequesterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequesterTypeGUID");

                    b.ToTable("RequesterTypes");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Code.Translation", b =>
                {
                    b.Property<Guid>("TranslationGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EntityGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ProductGUID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TranslationGUID");

                    b.HasIndex("ProductGUID");

                    b.ToTable("Translations");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Code.WarehosueFocalPoint", b =>
                {
                    b.Property<Guid>("WarehosueFocalPointGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserFocalPointId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("WarehouseGUID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("WarehosueFocalPointGUID");

                    b.HasIndex("UserFocalPointId");

                    b.HasIndex("WarehouseGUID");

                    b.ToTable("WarehosueFocalPoints");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Code.Warehouse", b =>
                {
                    b.Property<Guid>("WarehouseGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("CreateDate")
                        .HasColumnType("date");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("DutyStationGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("UpdateDate")
                        .HasColumnType("date");

                    b.Property<string>("UpdatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WarehouseCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WarehouseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("WarehouseParentGUID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("WarehouseGUID");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DutyStationGUID");

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Enntry.EntryDetail", b =>
                {
                    b.Property<Guid>("EntryDetailGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("CreateDate")
                        .HasColumnType("date");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("CurrentMovementStatusGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CurrentOwnedWarehousGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CurrentPhysicalStatusGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CurrentProductStatusGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CurrentUSDPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ShipmentDate")
                        .HasColumnType("date");

                    b.Property<Guid>("ShipmentRequestDetailGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EntryDetailGUID");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ShipmentRequestDetailGUID");

                    b.ToTable("EntryDetails");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Enntry.EntryDeterminer", b =>
                {
                    b.Property<Guid>("EntryDeterminerGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DeterminerTypeGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeterminerValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EntryDetailGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EntryDeterminerGUID");

                    b.ToTable("EntryDeterminers");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Enntry.EntryMovement", b =>
                {
                    b.Property<Guid>("EntryMovementGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("CreateDate")
                        .HasColumnType("date");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("EntryDetailGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FlowStatusGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsLastAction")
                        .HasColumnType("bit");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("UpdateDate")
                        .HasColumnType("date");

                    b.Property<string>("UpdatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EntryMovementGUID");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("EntryMovements");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Entry.EntryDetailPrice", b =>
                {
                    b.Property<Guid>("EntryDetailPriceGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EntryDetailGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PriceTypeGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PriceValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UpdatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EntryDetailPriceGUID");

                    b.ToTable("EntryDetailPrices");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Release.ReleaseRequest", b =>
                {
                    b.Property<Guid>("ReleaseRequestGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("CreateDate")
                        .HasColumnType("date");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LastRequestStatusGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RequestNameGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RequestTypeGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SequenceCode")
                        .HasColumnType("int");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("int");

                    b.Property<DateOnly>("UpdateDate")
                        .HasColumnType("date");

                    b.Property<string>("UpdatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserCreatorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("WarehouseUserGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("YearId")
                        .HasColumnType("int");

                    b.HasKey("ReleaseRequestGUID");

                    b.HasIndex("RequestTypeGUID");

                    b.HasIndex("UserCreatorId");

                    b.ToTable("ReleaseRequests");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Release.ReleaseRequestDetail", b =>
                {
                    b.Property<Guid>("ReleaseRequestDetailGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("CreateDate")
                        .HasColumnType("date");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("D")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EntryDetailGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EntryDetailPriceGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("ReleaseRequestGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("UpdateDate")
                        .HasColumnType("date");

                    b.Property<string>("UpdatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReleaseRequestDetailGUID");

                    b.ToTable("ReleaseRequestDetails");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Release.ReleaseRequestMovement", b =>
                {
                    b.Property<Guid>("ReleaseRequestMovementGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("CreateDate")
                        .HasColumnType("date");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FlowStatusGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsLastAction")
                        .HasColumnType("bit");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<Guid>("ReleaseRequestGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("UpdateDate")
                        .HasColumnType("date");

                    b.Property<string>("UpdatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserCreatorId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ReleaseRequestMovementGUID");

                    b.HasIndex("UserCreatorId");

                    b.ToTable("ReleaseRequestMovements");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Shipment.ShipmentRequest", b =>
                {
                    b.Property<Guid>("ShipmentRequestGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("CreateDate")
                        .HasColumnType("date");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ShipmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ShipmentNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("ShipmentTypeGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SupplierGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("UpdateDate")
                        .HasColumnType("date");

                    b.Property<string>("UpdatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("WarehouseGUID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ShipmentRequestGUID");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("SupplierGUID");

                    b.HasIndex("WarehouseGUID");

                    b.ToTable("ShipmentRequests");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Shipment.ShipmentRequestDetail", b =>
                {
                    b.Property<Guid>("ShipmentRequestDetailGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("CreateDate")
                        .HasColumnType("date");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("EruoPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LocalCurrencyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("ShipmentRequestGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("USDPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("UpdateDate")
                        .HasColumnType("date");

                    b.Property<string>("UpdatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("WarehoudGUID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ShipmentRequestDetailGUID");

                    b.HasIndex("ProductGUID");

                    b.HasIndex("ShipmentRequestGUID");

                    b.ToTable("ShipmentRequestDetails");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Shipment.ShipmentRequestMovement", b =>
                {
                    b.Property<Guid>("ShipmentRequestMovementGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("CreateDate")
                        .HasColumnType("date");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("FlowStatusGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsLastAction")
                        .HasColumnType("bit");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<Guid>("ShipmentRequestGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("UpdateDate")
                        .HasColumnType("date");

                    b.Property<string>("UpdatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShipmentRequestMovementGUID");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ShipmentRequestGUID");

                    b.ToTable("ShipmentRequestMovements");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Shipment.Supplier", b =>
                {
                    b.Property<Guid>("SupplierGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("CreateDate")
                        .HasColumnType("date");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LocationGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("UpdateDate")
                        .HasColumnType("date");

                    b.Property<string>("UpdatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserCreatorId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SupplierGUID");

                    b.HasIndex("LocationGUID");

                    b.HasIndex("UserCreatorId");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("WHS.Domain.Entities.Account.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("WHS.Domain.Entities.Account.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WHS.Domain.Entities.Account.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("WHS.Domain.Entities.Account.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WHS.Domain.Entities.Code.CodeTable", b =>
                {
                    b.HasOne("WHS.Domain.Entities.Account.User", "UserCreator")
                        .WithMany("OwnedCodeTables")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserCreator");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Code.CodeTableValue", b =>
                {
                    b.HasOne("WHS.Domain.Entities.Code.CodeTable", "CodeTable")
                        .WithMany("CodeTableValues")
                        .HasForeignKey("TableGUID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CodeTable");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Code.CountryLocation", b =>
                {
                    b.HasOne("WHS.Domain.Entities.Code.Country", "Country")
                        .WithMany("CountryLocations")
                        .HasForeignKey("CountryGUID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Code.DutyStation", b =>
                {
                    b.HasOne("WHS.Domain.Entities.Code.InstitutionByCountry", "InstitutionByCountry")
                        .WithMany("DutyStations")
                        .HasForeignKey("InstitutionGUID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InstitutionByCountry");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Code.InstitutionByCountry", b =>
                {
                    b.HasOne("WHS.Domain.Entities.Code.Country", "Country")
                        .WithMany("InstitutionByCountries")
                        .HasForeignKey("CountryGUID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WHS.Domain.Entities.Code.Organization", "Organization")
                        .WithMany("InstitutionByCountries")
                        .HasForeignKey("OrganizationGUID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Code.Product", b =>
                {
                    b.HasOne("WHS.Domain.Entities.Code.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandGUID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WHS.Domain.Entities.Code.ProductSubCategory", "ProductSubCategory")
                        .WithMany("Products")
                        .HasForeignKey("ProductSubCategoryGUID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WHS.Domain.Entities.Code.ProductType", "ProductType")
                        .WithMany("Products")
                        .HasForeignKey("ProductTypeGUID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("ProductSubCategory");

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Code.ProductByWarehouse", b =>
                {
                    b.HasOne("WHS.Domain.Entities.Code.Product", "Product")
                        .WithMany("ProductByWarehouses")
                        .HasForeignKey("ProductGUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WHS.Domain.Entities.Code.Warehouse", "Warehouse")
                        .WithMany("ProductByWarehouses")
                        .HasForeignKey("WarehouseGUID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Code.ProductDeterminer", b =>
                {
                    b.HasOne("WHS.Domain.Entities.Code.DeterminerType", "DeterminerType")
                        .WithMany("ProductDeterminers")
                        .HasForeignKey("DeterminerTypeGUID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WHS.Domain.Entities.Code.Product", "Product")
                        .WithMany("Determiners")
                        .HasForeignKey("ProductGUID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DeterminerType");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Code.ProductFeature", b =>
                {
                    b.HasOne("WHS.Domain.Entities.Code.Product", "Product")
                        .WithMany("Features")
                        .HasForeignKey("ProductGUID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Code.ProductSubCategory", b =>
                {
                    b.HasOne("WHS.Domain.Entities.Code.ProductCategory", "ProductCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ProductCategoryGUID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Code.Translation", b =>
                {
                    b.HasOne("WHS.Domain.Entities.Code.Product", null)
                        .WithMany("Translations")
                        .HasForeignKey("ProductGUID");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Code.WarehosueFocalPoint", b =>
                {
                    b.HasOne("WHS.Domain.Entities.Account.User", "UserFocalPoint")
                        .WithMany("WarehosueFocalPoints")
                        .HasForeignKey("UserFocalPointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WHS.Domain.Entities.Code.Warehouse", "Warehouse")
                        .WithMany("WarehosueFocalPoints")
                        .HasForeignKey("WarehouseGUID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserFocalPoint");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Code.Warehouse", b =>
                {
                    b.HasOne("WHS.Domain.Entities.Account.User", "UserCreator")
                        .WithMany("CreatedWarehouses")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WHS.Domain.Entities.Code.DutyStation", "DutyStation")
                        .WithMany("Warehouses")
                        .HasForeignKey("DutyStationGUID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DutyStation");

                    b.Navigation("UserCreator");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Enntry.EntryDetail", b =>
                {
                    b.HasOne("WHS.Domain.Entities.Account.User", "UserCreator")
                        .WithMany("EntryDetails")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WHS.Domain.Entities.Shipment.ShipmentRequestDetail", "ShipmentRequestDetail")
                        .WithMany("EntryDetails")
                        .HasForeignKey("ShipmentRequestDetailGUID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ShipmentRequestDetail");

                    b.Navigation("UserCreator");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Enntry.EntryDeterminer", b =>
                {
                    b.HasOne("WHS.Domain.Entities.Enntry.EntryDetail", "EntryDetail")
                        .WithMany("EntryDeterminers")
                        .HasForeignKey("EntryDeterminerGUID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EntryDetail");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Enntry.EntryMovement", b =>
                {
                    b.HasOne("WHS.Domain.Entities.Account.User", "UserCreator")
                        .WithMany("EntryMovements")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WHS.Domain.Entities.Enntry.EntryDetail", "EntryDetail")
                        .WithMany("EntryMovements")
                        .HasForeignKey("EntryMovementGUID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EntryDetail");

                    b.Navigation("UserCreator");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Entry.EntryDetailPrice", b =>
                {
                    b.HasOne("WHS.Domain.Entities.Enntry.EntryDetail", "EntryDetail")
                        .WithMany("EntryDetailPrices")
                        .HasForeignKey("EntryDetailPriceGUID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EntryDetail");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Release.ReleaseRequest", b =>
                {
                    b.HasOne("WHS.Domain.Entities.Code.RequesterType", "RequesterType")
                        .WithMany("ReleaseRequests")
                        .HasForeignKey("RequestTypeGUID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WHS.Domain.Entities.Account.User", "UserCreator")
                        .WithMany("ReleaseRequests")
                        .HasForeignKey("UserCreatorId");

                    b.Navigation("RequesterType");

                    b.Navigation("UserCreator");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Release.ReleaseRequestDetail", b =>
                {
                    b.HasOne("WHS.Domain.Entities.Enntry.EntryDetail", "EntryDetail")
                        .WithMany("ReleaseRequestDetails")
                        .HasForeignKey("ReleaseRequestDetailGUID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WHS.Domain.Entities.Entry.EntryDetailPrice", "EntryDetailPrice")
                        .WithMany("ReleaseRequestDetails")
                        .HasForeignKey("ReleaseRequestDetailGUID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WHS.Domain.Entities.Release.ReleaseRequest", "ReleaseRequest")
                        .WithMany("ReleaseRequestDetails")
                        .HasForeignKey("ReleaseRequestDetailGUID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EntryDetail");

                    b.Navigation("EntryDetailPrice");

                    b.Navigation("ReleaseRequest");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Release.ReleaseRequestMovement", b =>
                {
                    b.HasOne("WHS.Domain.Entities.Release.ReleaseRequest", "ReleaseRequest")
                        .WithMany("ReleaseRequestMovements")
                        .HasForeignKey("ReleaseRequestMovementGUID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WHS.Domain.Entities.Account.User", "UserCreator")
                        .WithMany("ReleaseRequestMovements")
                        .HasForeignKey("UserCreatorId");

                    b.Navigation("ReleaseRequest");

                    b.Navigation("UserCreator");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Shipment.ShipmentRequest", b =>
                {
                    b.HasOne("WHS.Domain.Entities.Account.User", "UserCreator")
                        .WithMany("ShipmentRequests")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WHS.Domain.Entities.Shipment.Supplier", "Supplier")
                        .WithMany("ShipmentRequests")
                        .HasForeignKey("SupplierGUID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WHS.Domain.Entities.Code.Warehouse", "Warehouse")
                        .WithMany("ShipmentRequests")
                        .HasForeignKey("WarehouseGUID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supplier");

                    b.Navigation("UserCreator");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Shipment.ShipmentRequestDetail", b =>
                {
                    b.HasOne("WHS.Domain.Entities.Code.Product", "Product")
                        .WithMany("ShipmentRequestDetails")
                        .HasForeignKey("ProductGUID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WHS.Domain.Entities.Shipment.ShipmentRequest", "ShipmentRequest")
                        .WithMany("ShipmentDetails")
                        .HasForeignKey("ShipmentRequestGUID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ShipmentRequest");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Shipment.ShipmentRequestMovement", b =>
                {
                    b.HasOne("WHS.Domain.Entities.Account.User", "UserCreator")
                        .WithMany("ShipmentRequestMovements")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WHS.Domain.Entities.Shipment.ShipmentRequest", "ShipmentRequest")
                        .WithMany("ShipmentRequestMovements")
                        .HasForeignKey("ShipmentRequestGUID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ShipmentRequest");

                    b.Navigation("UserCreator");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Shipment.Supplier", b =>
                {
                    b.HasOne("WHS.Domain.Entities.Code.CountryLocation", "CountryLocation")
                        .WithMany("Suppliers")
                        .HasForeignKey("LocationGUID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WHS.Domain.Entities.Account.User", "UserCreator")
                        .WithMany("Suppliers")
                        .HasForeignKey("UserCreatorId");

                    b.Navigation("CountryLocation");

                    b.Navigation("UserCreator");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Account.User", b =>
                {
                    b.Navigation("CreatedWarehouses");

                    b.Navigation("EntryDetails");

                    b.Navigation("EntryMovements");

                    b.Navigation("OwnedCodeTables");

                    b.Navigation("ReleaseRequestMovements");

                    b.Navigation("ReleaseRequests");

                    b.Navigation("ShipmentRequestMovements");

                    b.Navigation("ShipmentRequests");

                    b.Navigation("Suppliers");

                    b.Navigation("WarehosueFocalPoints");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Code.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Code.CodeTable", b =>
                {
                    b.Navigation("CodeTableValues");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Code.Country", b =>
                {
                    b.Navigation("CountryLocations");

                    b.Navigation("InstitutionByCountries");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Code.CountryLocation", b =>
                {
                    b.Navigation("Suppliers");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Code.DeterminerType", b =>
                {
                    b.Navigation("ProductDeterminers");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Code.DutyStation", b =>
                {
                    b.Navigation("Warehouses");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Code.InstitutionByCountry", b =>
                {
                    b.Navigation("DutyStations");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Code.Organization", b =>
                {
                    b.Navigation("InstitutionByCountries");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Code.Product", b =>
                {
                    b.Navigation("Determiners");

                    b.Navigation("Features");

                    b.Navigation("ProductByWarehouses");

                    b.Navigation("ShipmentRequestDetails");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Code.ProductCategory", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Code.ProductSubCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Code.ProductType", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Code.RequesterType", b =>
                {
                    b.Navigation("ReleaseRequests");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Code.Warehouse", b =>
                {
                    b.Navigation("ProductByWarehouses");

                    b.Navigation("ShipmentRequests");

                    b.Navigation("WarehosueFocalPoints");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Enntry.EntryDetail", b =>
                {
                    b.Navigation("EntryDetailPrices");

                    b.Navigation("EntryDeterminers");

                    b.Navigation("EntryMovements");

                    b.Navigation("ReleaseRequestDetails");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Entry.EntryDetailPrice", b =>
                {
                    b.Navigation("ReleaseRequestDetails");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Release.ReleaseRequest", b =>
                {
                    b.Navigation("ReleaseRequestDetails");

                    b.Navigation("ReleaseRequestMovements");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Shipment.ShipmentRequest", b =>
                {
                    b.Navigation("ShipmentDetails");

                    b.Navigation("ShipmentRequestMovements");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Shipment.ShipmentRequestDetail", b =>
                {
                    b.Navigation("EntryDetails");
                });

            modelBuilder.Entity("WHS.Domain.Entities.Shipment.Supplier", b =>
                {
                    b.Navigation("ShipmentRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
